### ISSUE TITLE
Anh ơi có phiên bản buil cho dev c++ không ạ?

### ISSUE THREAD

**Issue by giahuyng98** [haint97/Do-an-CTDL-GT-PTIT-HCM--Quan-ly-may-bay#1]
anh có make file gì không cho em xin build chạy thử với.
Cảm ơn anh ạ.

**Comment by thaihai-swe** [comment]
không, a chỉ build trên visual studio thôi, code này lâu rồi :D

**Comment by giahuyng98** [comment]
Dạ cảm ơn anh.
